import React, { useEffect, useState } from 'react';
import { Layout } from '../components';
import './globals.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'BG Blog',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<Layout>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</Layout>
	);
}
